[domain_name]
 [domain_name.KR]
 post = 'https://clnuioegyckvybeikrfc.supabase.co/functions/v1/post_license_log'
 put = 'https://clnuioegyckvybeikrfc.supabase.co/functions/v1/put_license_log'
 [domain_name.CN]
 post = ''
 put = ''
[[lookup_services]]
 url = 'https://clnuioegyckvybeikrfc.supabase.co/functions/v1/lookup-ip'
[[lookup_services]]
 url = 'https://www.ip.cn/api/index?ip=&type=0'